name: Code quality

on: [pull_requesr]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install black isort mypy ruff
      - name: Run linter
        run: black .
      - name: Run formatters
        run: isort --check . && isort --check . && mypy --check . && ruff --check .